### ISSUE TITLE
Data Cleaning (State Level)

### ISSUE THREAD

**Issue by k-oconnor** [k-oconnor/Housing_Price_Choropleth#6]
Standardize the pricing observations. (Z-scoring?)

**Comment by bowman-jonathan** [comment]
solved by converting date columns into rows to fulfill clean data definition of one observation per row

zillow_melt = zillow_raw.melt(
    id_vars=["STNAME", "CTYNAME"],
    value_vars=[
        "12/31/2010",
        "12/31/2011",
        "12/31/2012",
        "12/31/2013",
        "12/31/2014",
        "12/31/2015",
        "12/31/2016",
        "12/31/2017",
        "12/31/2018",
        "12/31/2019",
    ],
    var_name="DATE",
    value_name="PRICE",
)

census_melt = census_raw.melt(
    id_vars=["STNAME", "CTYNAME"],
    var_name="DATE", 
    value_name="POPULATION"
)
