### ISSUE TITLE
Get data set of population by county

### ISSUE THREAD

**Issue by KarloVlahek** [k-oconnor/Housing_Price_Choropleth#8]

**Comment by KarloVlahek** [comment]
Possible issue solved. The only caveat: this data set stems from 2010 - 2019. So, if we wanted the latest data set, this data is not it. From census gov, so credible data set.

[co-est2019-annres (1).xlsx](https://github.com/k-oconnor/Housing_Price_Chloropleth/files/8227598/co-est2019-annres.1.xlsx)

**Comment by amal-kadri** [comment]
Found the data set
